import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import "./globals.css";

import Footer from "@/components/footer";
import Header from "@/components/header";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body className={`${nunito.variable} antialiased pb-[119px]`}>
        <div className='min-h-screen font-[family-name:var(--font-nunito)]'>
          <Header />

          <main className='flex flex-col row-start-2 items-center px-4 py-6 overflow-y-scroll'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
